export interface PlacementQuestion {
  id: number;
  skill: string;
  skillAr: string;
  subSkillAr: string;
  cefr: string;
  question: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanationAr: string;
}

export const PLACEMENT_TEST_80_QUESTIONS: PlacementQuestion[] = [
  // 1. Letters & Phonetics (1-10)
  { id: 1, skill: 'letters', skillAr: 'الأصوات والحروف', subSkillAr: 'التمتع البصري والصوتي', cefr: 'A1', question: 'اختر الحرف الذي تبدأ به كلمة (أَرْنَبٌ):', options: ['أ', 'ب', 'ت', 'ث'], correctIndex: 0, explanationAr: 'تبدأ كلمة أَرْنَبٌ بحرف الألف (أ).' },
  { id: 2, skill: 'letters', skillAr: 'الأصوات والحروف', subSkillAr: 'أشكال الحروف في الكلمة', cefr: 'A1', question: 'ما هو الشكل المناسب لحرف الباء في أول كلمة (بَطَّةٌ)؟', options: ['بـ', 'ـبـ', 'ـب', 'ب'], correctIndex: 0, explanationAr: 'في أول الكلمة يكتب حرف الباء متصلاً بما بعده (بـ).' },
  { id: 3, skill: 'letters', skillAr: 'الأصوات والحروف', subSkillAr: 'الحركات والأصوات الطويلة', cefr: 'A1', question: 'اختر الصوت الطويل (حرف المد) في كلمة (كِتَابٌ):', options: ['الواو', 'الألف', 'الياء', 'الفتحة'], correctIndex: 1, explanationAr: 'المد بالألف يتبع الحركة المفتوحة (تَا).' },
  { id: 4, skill: 'letters', skillAr: 'الأصوات والحروف', subSkillAr: 'الحركات القصيرة', cefr: 'A1', question: 'ما هو الصوت الأول بالتشكيل في كلمة (ثُعْبَانٌ)؟', options: ['ثُ', 'ثِ', 'ثَ', 'ثْ'], correctIndex: 0, explanationAr: 'الصوت الأول هو ثُ بالضمة.' },
  { id: 5, skill: 'letters', skillAr: 'الأصوات والحروف', subSkillAr: 'التمييز السمعي والبصري', cefr: 'A1', question: 'اختر الكلمة التي تبدأ بـ (حرف الحاء):', options: ['حِصَانٌ', 'خَرُوفٌ', 'جَمَلٌ', 'دِيكٌ'], correctIndex: 0, explanationAr: 'كلمة حِصَانٌ تبدأ بالحاء المكسورة (حِ).' },
  { id: 6, skill: 'letters', skillAr: 'الأصوات والحروف', subSkillAr: 'التمييز بين الحروف', cefr: 'A1', question: 'الحرف المضموم في كلمة (ذُرَةٌ) هو:', options: ['حرف الذال', 'حرف الراء', 'التاء المربوطة', 'حرف الألف'], correctIndex: 0, explanationAr: 'الذال مضمومة (ذُ).' },
  { id: 7, skill: 'letters', skillAr: 'الأصوات والحروف', subSkillAr: 'اللام الشمسية والقمرية', cefr: 'A2', question: 'أيّ من الكلمات التالية تحتوي على (اللام الشمسية)؟', options: ['الشَّمْسُ', 'القَمَرُ', 'البَابُ', 'المَدْرَسَةُ'], correctIndex: 0, explanationAr: 'حرف الشين من الحروف الشمسية واللام لا تُنطق.' },
  { id: 8, skill: 'letters', skillAr: 'الأصوات والحروف', subSkillAr: 'التاء المربوطة والرموز', cefr: 'A2', question: 'اختر الكلمة التي تنتهي بـ (تاء مربوطة):', options: ['زَهْرَةٌ', 'زَيْتٌ', 'بَنَاتٌ', 'بَيْتٌ'], correctIndex: 0, explanationAr: 'تنتهي زَهْرَةٌ بتاء مربوطة (ةٌ).' },
  { id: 9, skill: 'letters', skillAr: 'الأصوات والحروف', subSkillAr: 'التنوين ورسمه', cefr: 'A2', question: 'التنوين بالضم في كلمة (عِنَبٌ) يظهر على حرف:', options: ['الباء', 'النون', 'العين', 'الألف'], correctIndex: 0, explanationAr: 'التنوين يوضع على الحرف الأخير وهو الباء.' },
  { id: 10, skill: 'letters', skillAr: 'الأصوات والحروف', subSkillAr: 'تركيب الكلمات من الحروف', cefr: 'A2', question: 'ما الكلمة الصحيحة إملاءً عند تجميع الحروف (س - مـ - ـكـ - ـة)؟', options: ['سَمَكَةٌ', 'سَمَكَتٌ', 'صَمَكَةٌ', 'سَمَكً'], correctIndex: 0, explanationAr: 'التجميع الصحيح للحروف يعطي كلمة سَمَكَةٌ.' },

  // 2. Vocabulary & Semantics (11-20)
  { id: 11, skill: 'vocab', skillAr: 'المفردات والتراكيب', subSkillAr: 'المترادفات', cefr: 'A1', question: 'مرادف كلمة (جَمِيلٌ) هو:', options: ['رَائِعٌ', 'قَبِيحٌ', 'صَغِيرٌ', 'بَطِيءٌ'], correctIndex: 0, explanationAr: 'جميل ورائع يعبران عن نفس المعنى.' },
  { id: 12, skill: 'vocab', skillAr: 'المفردات والتراكيب', subSkillAr: 'الأضداد', cefr: 'A1', question: 'ضدّ كلمة (كَبِيرٌ) هو:', options: ['صَغِيرٌ', 'طَوِيلٌ', 'كَثِيرٌ', 'سَرِيعٌ'], correctIndex: 0, explanationAr: 'عكس كبير هو صغير.' },
  { id: 13, skill: 'vocab', skillAr: 'المفردات والتراكيب', subSkillAr: 'الحقول الدلالية والكلمة الغريبة', cefr: 'A1', question: 'الكلمة الغريبة التي لا تنتمي للمجموعة (تُفَّاحَةٌ - مَوْزٌ - لَيْمُونٌ - كِتَابٌ) هي:', options: ['كِتَابٌ', 'تُفَّاحَةٌ', 'مَوْزٌ', 'لَيْمُونٌ'], correctIndex: 0, explanationAr: 'الكتاب ليس من الفواكه.' },
  { id: 14, skill: 'vocab', skillAr: 'المفردات والتراكيب', subSkillAr: 'الأماكن والمحيط الاجتماعي', cefr: 'A2', question: 'المكان الذي نشتري منه الأطعمة والخضروات يُسمّى:', options: ['السُّوقُ', 'المَكْتَبَةُ', 'المَلْعَبُ', 'المَطَارُ'], correctIndex: 0, explanationAr: 'السوق هو مكان الشراء والبيع.' },
  { id: 15, skill: 'vocab', skillAr: 'المفردات والتراكيب', subSkillAr: 'الجموع وأنواعها', cefr: 'A2', question: 'الجمع المناسب لكلمة (طَالِبٌ) هو:', options: ['طُلاَّبٌ', 'طَالِبَاتٌ', 'طَالِبُونَ', 'طَوَالِبُ'], correctIndex: 0, explanationAr: 'جمع طََالِب هو طُلاَّب (جمع تكسير).' },
  { id: 16, skill: 'vocab', skillAr: 'المفردات والتراكيب', subSkillAr: 'المفرد والجمع', cefr: 'A2', question: 'مفرد كلمة (أَشْجَارٌ) هو:', options: ['شَجَرَةٌ', 'شَاجِرٌ', 'شَجَرٌ', 'مُشَجَّرٌ'], correctIndex: 0, explanationAr: 'مفرد أشجار هو شَجَرَةٌ.' },
  { id: 17, skill: 'vocab', skillAr: 'المفردات والتراكيب', subSkillAr: 'المهن الوظائف', cefr: 'A2', question: 'الشخص الذي يعالج المرضى في المستشفى هو:', options: ['الطَّبِيبُ', 'المُنَادِي', 'المُهَنْدِسُ', 'السَّائِقُ'], correctIndex: 0, explanationAr: 'الطبيب يعالج المرضى.' },
  { id: 18, skill: 'vocab', skillAr: 'المفردات والتراكيب', subSkillAr: 'الفهم الدلالي المتقدم', cefr: 'B1', question: 'ما معنى كلمة (سَرِيعٌ)؟', options: ['يتحرك بمهل وعكس البطء', 'ثابت في مكانه', 'بطيء الحركة', 'متوقف تماماً'], correctIndex: 0, explanationAr: 'السريع هو الذي ينقل بين النقطتين بزمن قصير.' },
  { id: 19, skill: 'vocab', skillAr: 'المفردات والتراكيب', subSkillAr: 'السياق والملاءمة اللفظية', cefr: 'B1', question: 'اختر الكلمة المناسبة للجملة: شَرِبْتُ (...) مِنَ المَاءِ البَارِدِ.', options: ['كُوباً', 'كِتَاباً', 'قَلَماً', 'جِدَاراً'], correctIndex: 0, explanationAr: 'كوباً تتلاءم مع شرب الماء.' },
  { id: 20, skill: 'vocab', skillAr: 'المفردات والتراكيب', subSkillAr: 'المترادفات المتقدمة', cefr: 'B1', question: 'مرادف كلمة (سَعِيدٌ) هو:', options: ['مَسْرُورٌ', 'حَزِينٌ', 'غَاضِبٌ', 'خَائِفٌ'], correctIndex: 0, explanationAr: 'السعيد هو المسرور والفرح.' },

  // 3. Grammar & Syntax (21-30)
  { id: 21, skill: 'grammar', skillAr: 'القواعد والنحو', subSkillAr: 'الضمائر الشخصية', cefr: 'A1', question: 'اختر الضمير المناسب: (...) طَالِبٌ مُجْتَهِدٌ.', options: ['هُوَ', 'هِيَ', 'هُمْ', 'هُنَّ'], correctIndex: 0, explanationAr: 'هو للمفرد المذكر الغائب.' },
  { id: 22, skill: 'grammar', skillAr: 'القواعد والنحو', subSkillAr: 'مطابقة الفعل مع الفاعل', cefr: 'A1', question: 'اختر الفعل المناسب للجملة: الطَّالِبَةُ (...) الدَّرْسَ.', options: ['تَكْتُبُ', 'يَكْتُبُ', 'يَكْتُبُونَ', 'اكْتُبْ'], correctIndex: 0, explanationAr: 'تكتب للمؤنث المفرد المضارع.' },
  { id: 23, skill: 'grammar', skillAr: 'القواعد والنحو', subSkillAr: 'أسماء الإشارة', cefr: 'A1', question: 'اسم الإشارة المناسب للمفرد المؤنث القريب هو:', options: ['هَذِهِ', 'هَذَا', 'هَؤُلاءِ', 'ذَلِكَ'], correctIndex: 0, explanationAr: 'هذه تُستخدم للمفرد المؤنث القريب.' },
  { id: 24, skill: 'grammar', skillAr: 'القواعد والنحو', subSkillAr: 'حروف الجر', cefr: 'A2', question: 'اختر حرف الجر المناسب: ذَهَبَ أَحْمَدُ (...) المَدْرَسَةِ.', options: ['إِلَى', 'عَنْ', 'عَلَى', 'فِي'], correctIndex: 0, explanationAr: 'إلى يفيد الانتهاء والمكان المجهود.' },
  { id: 25, skill: 'grammar', skillAr: 'القواعد والنحو', subSkillAr: 'أقسام الكلام والجملة الاسمية', cefr: 'A2', question: 'الجملة الاسمية هي الجملة التي تبدأ بـ:', options: ['اسم', 'فعل', 'حرف', 'ظرف'], correctIndex: 0, explanationAr: 'تتكون الجملة الاسمية من مبتدأ وخبر وتصدر باسم.' },
  { id: 26, skill: 'grammar', skillAr: 'القواعد والنحو', subSkillAr: 'أركان الجملة الفعلية', cefr: 'A2', question: 'الفاعل في جملة (قَرَأَ المُعَلِّمُ الكِتَابَ) هو:', options: ['المُعَلِّمُ', 'قَرَأَ', 'الكِتَابَ', 'ضمير مستتر'], correctIndex: 0, explanationAr: 'المعلم هو من قام بالفعل مرفوع بالضمة.' },
  { id: 27, skill: 'grammar', skillAr: 'القواعد والنحو', subSkillAr: 'أزمنة الأفعال', cefr: 'B1', question: 'الفعل (يَلْعَبُ) هو فعل:', options: ['مُضَارِعٌ', 'مَاضٍ', 'أَمْرٌ', 'مَبْنِيٌّ لِلْمَجْهُولِ'], correctIndex: 0, explanationAr: 'بدأ بياء المضارعة ويدل على الحاضر.' },
  { id: 28, skill: 'grammar', skillAr: 'القواعد والنحو', subSkillAr: 'علامات الإعراب الأصلية', cefr: 'B1', question: 'العلامة الإعرابية المرفوعة للفاعل المفرد هي:', options: ['الضَّمَّةُ', 'الفَتْحَةُ', 'الكَسْرَةُ', 'السُّكُونُ'], correctIndex: 0, explanationAr: 'الضمة هي علامة الرفع الأصلية.' },
  { id: 29, skill: 'grammar', skillAr: 'القواعد والنحو', subSkillAr: 'المفعول به وتشكيله', cefr: 'B1', question: 'اختر التشكيل الصحيح للمفعول به في: شَرِبَ الوَلَدُ (...)', options: ['المَاءَ', 'المَاءُ', 'المَاءِ', 'مَاءٌ'], correctIndex: 0, explanationAr: 'المفعول به منصوب وعلامة نصبه الفتحة (المَاءَ).' },
  { id: 30, skill: 'grammar', skillAr: 'القواعد والنحو', subSkillAr: 'العدد والمعدود والتراكيب', cefr: 'B2', question: 'اختر العدد والمعدود الصحيح تركيباً:', options: ['أَرْبَعَةُ طُلاَّبٍ', 'أَرْبَعُ طُلاَّبٍ', 'أَرْبَعَةُ طَالِبٍ', 'أَرْبَعَةَ طُلاَّبًا'], correctIndex: 0, explanationAr: 'الأعداد من 3-10 تخالف المعدود والمعدود جمع مجرور.' },

  // 4. Translation & Dual Proficiency (31-40)
  { id: 31, skill: 'translator', skillAr: 'الترجمة والفهم المزدوج', subSkillAr: 'المفردات الأساسية', cefr: 'A1', question: 'اختر الترجمة العربية الصحيحة لكلمة: "School"', options: ['مَدْرَسَة', 'بَيْت', 'مَكْتَبَة', 'مَطَار'], correctIndex: 0, explanationAr: 'School تعني مَدْرَسَة.' },
  { id: 32, skill: 'translator', skillAr: 'الترجمة والفهم المزدوج', subSkillAr: 'التحيات اليومية', cefr: 'A1', question: 'اختر الترجمة العربية الصحيحة لـ: "Good morning"', options: ['صَبَاحُ الخَيْرِ', 'مَسَاءُ الخَيْرِ', 'أَهْلاً وَسَهْلاً', 'مَعَ السَّلامَةِ'], correctIndex: 0, explanationAr: 'Good morning هي صباح الخير.' },
  { id: 33, skill: 'translator', skillAr: 'الترجمة والفهم المزدوج', subSkillAr: 'الجمل البسيطة', cefr: 'A2', question: 'اختر الترجمة الصحيحة لجملة: "I love reading books"', options: ['أُحِبُّ قِرَاءَةَ الكُتُبِ', 'أُحِبُّ كِتَابَةَ الرَّسَائِلِ', 'أَقْرَأُ الكِتَابَ الآنَ', 'أُحِبُّ شِرَاءَ الكُتُبِ'], correctIndex: 0, explanationAr: 'reading books تعني قراءة الكتب.' },
  { id: 34, skill: 'translator', skillAr: 'الترجمة والفهم المزدوج', subSkillAr: 'مصطلحات المهن', cefr: 'A2', question: 'ما الترجمة الدقيقة لكلمة: "Doctor"', options: ['طَبِيبٌ', 'مُهَنْدِسٌ', 'مُعَلِّمٌ', 'شُرْطِيٌّ'], correctIndex: 0, explanationAr: 'Doctor هو طبيب.' },
  { id: 35, skill: 'translator', skillAr: 'الترجمة والفهم المزدوج', subSkillAr: 'التطبيقات الاجتماعية', cefr: 'A2', question: 'اختر المعنى العربي المناسب للتعبير: "Welcome to our home"', options: ['مَرْحَبًا بِكُمْ فِي بَيْتِنَا', 'أَهْلاً بِكُمْ فِي مَدْرَسَتِنَا', 'شُكْرًا لِزِيَارَتِكُمْ', 'مَعَ السَّلامَةِ فِي بَيْتِكُمْ'], correctIndex: 0, explanationAr: 'our home يعني بيتنا.' },
  { id: 36, skill: 'translator', skillAr: 'الترجمة والفهم المزدوج', subSkillAr: 'الوصف البيئي والطقس', cefr: 'B1', question: 'Translate to Arabic: "The weather is nice today"', options: ['الطَّقْسُ جَمِيلٌ اليَوْمَ', 'المَطَرُ غَزِيرٌ اليَوْمَ', 'الشَّمْسُ سَاطِعَةٌ أَمْسِ', 'الجَوُّ بَارِدٌ جِدًّا'], correctIndex: 0, explanationAr: 'weather is nice يعني الطقس جميل.' },
  { id: 37, skill: 'translator', skillAr: 'الترجمة والفهم المزدوج', subSkillAr: 'السياق والعمل', cefr: 'B1', question: 'اختر المعنى العربي الصحيح لجملة: "She works at a university"', options: ['هِيَ تَعْمَلُ فِي جَامِعَةٍ', 'هِيَ تَعْمَلُ فِي المَكْتَبَةِ', 'هِيَ تَدْرُسُ فِي المَدْرَسَةِ', 'هِيَ تُعَلِّمُ فِي المَكْتَبِ'], correctIndex: 0, explanationAr: 'university تعني جامعة.' },
  { id: 38, skill: 'translator', skillAr: 'الترجمة والفهم المزدوج', subSkillAr: 'الأسئلة والاستفسارات', cefr: 'A1', question: 'What is the correct English rendering of "مَا اسْمُكَ؟":', options: ['What is your name?', 'Where are you from?', 'How old are you?', 'How are you?'], correctIndex: 0, explanationAr: 'ما اسمك تعني What is your name.' },
  { id: 39, skill: 'translator', skillAr: 'الترجمة والفهم المزدوج', subSkillAr: 'الترجمة الاصطلاحية', cefr: 'B2', question: 'اختر التعبير العربي الأدق لـ: "Take care of yourself"', options: ['اعْتَنِ بِنَفْسِكَ', 'كُنْ سَرِيعاً', 'لا تَخَفْ', 'سَافِرْ بِسَلامٍ'], correctIndex: 0, explanationAr: 'Take care of yourself يعني اعتَنِ بنفسك.' },
  { id: 40, skill: 'translator', skillAr: 'الترجمة والفهم المزدوج', subSkillAr: 'الأمثال والحكم', cefr: 'B2', question: 'اختر الترجمة الصحيحة لـ: "Knowledge is light"', options: ['العِلْمُ نُورٌ', 'العِلْمُ قُوَّةٌ', 'المَعْرِفَةُ كَنْزٌ', 'القِرَاءَةُ مُفِيدَةٌ'], correctIndex: 0, explanationAr: 'Knowledge is light تعني العلم نور.' },

  // 5. Listening Comprehension (41-50)
  { id: 41, skill: 'listening', skillAr: 'الاستماع والفهم المسموع', subSkillAr: 'ردود التحيات', cefr: 'A1', question: 'عند سماع التحية "السَّلامُ عَلَيْكُمْ"، تكون الإجابة المناسبة هي:', options: ['وَعَلَيْكُمُ السَّلامُ', 'صَبَاحُ الخَيْرِ', 'أَهْلاً وَسَهْلاً', 'شُكْرًا جَزِيلاً'], correctIndex: 0, explanationAr: 'رد سلام المسلم هو وعليكم السلام.' },
  { id: 42, skill: 'listening', skillAr: 'الاستماع والفهم المسموع', subSkillAr: 'الردود الاجتماعية', cefr: 'A1', question: 'قال لك شخص: "شُكْرًا جَزِيلاً"، ماذا تردّ عليه؟', options: ['عَفْواً', 'أَهْلاً', 'مَعَ السَّلامَةِ', 'نَعَمْ'], correctIndex: 0, explanationAr: 'الرد المناسب لشُكراً هو عَفواً.' },
  { id: 43, skill: 'listening', skillAr: 'الاستماع والفهم المسموع', subSkillAr: 'تحليل السؤال المسموع', cefr: 'A2', question: 'سمعتَ الجملة: "أَنَا أَسْكُنُ فِي مَدِينَةِ الرِّيَاضِ". السؤال المباشر لها هو:', options: ['أَيْنَ تَسْكُنُ؟', 'مَا اسْمُكَ؟', 'مَنْ أَنْتَ؟', 'كَيْفَ حَالُكَ؟'], correctIndex: 0, explanationAr: 'أين تسكن تسأل عن مكان السكن.' },
  { id: 44, skill: 'listening', skillAr: 'الاستماع والفهم المسموع', subSkillAr: 'المحادثات المباشرة', cefr: 'A1', question: 'عندما تسمع "كَيْفَ حَالُكَ؟"، تجيب بـ:', options: ['بِخَيْرٍ وَالْحَمْدُ لِلَّهِ', 'عُمْرِي عِشْرُونَ سَنَةً', 'أَنَا طَالِبٌ', 'اسْمِي خَالِدٌ'], correctIndex: 0, explanationAr: 'الرد على السؤال عن الحال هو بخير والحمد لله.' },
  { id: 45, skill: 'listening', skillAr: 'الاستماع والفهم المسموع', subSkillAr: 'تحديد الاتجاهات والمواقع', cefr: 'A2', question: 'استماع حوار: "أَيْنَ المَكْتَبَةُ؟ - المَكْتَبَةُ بِجَانِبِ المَسْجِدِ." أين تقع المَكْتَبَةُ؟', options: ['بِجَانِبِ المَسْجِدِ', 'أَمَامَ المَدْرَسَةِ', 'خَلْفَ البَيْتِ', 'فِي المَطَارِ'], correctIndex: 0, explanationAr: 'تحديد المكان المسموع صراحة هو بجانب المسجد.' },
  { id: 46, skill: 'listening', skillAr: 'الاستماع والفهم المسموع', subSkillAr: 'استخلاص الظروف والزمان', cefr: 'B1', question: 'استمعتَ للنصّ: "تَسْقُطُ الأَمْطَارُ فِي فَصْلِ الشِّتَاءِ". مَتَى تَسْقُطُ الأَمْطَارُ؟', options: ['فِي الشِّتَاءِ', 'فِي الصَّيْفِ', 'فِي الرَّبِيعِ', 'فِي الخَرِيفِ'], correctIndex: 0, explanationAr: 'المعلومة المسموعة في الشتاء.' },
  { id: 47, skill: 'listening', skillAr: 'الاستماع والفهم المسموع', subSkillAr: 'الإعلانات والأوقات', cefr: 'A2', question: 'استمعتَ لإعلان: "المَطْعَمُ يَفْتَحُ السَّاعَةَ السَّابِعَةَ صَبَاحاً". يَبْدَأُ المَطْعَمُ عَمَلَهُ:', options: ['صَبَاحاً', 'مَسَاءً', 'ظُهْراً', 'لَيْلاً'], correctIndex: 0, explanationAr: 'الافتتاح صباحاً.' },
  { id: 48, skill: 'listening', skillAr: 'الاستماع والفهم المسموع', subSkillAr: 'استخلاص التفضيلات والمشاعر', cefr: 'B1', question: 'استمعتَ للحوار: "هَلْ تُحِبُّ القَهْوَةَ؟ - لا، أُفَضِّلُ الشَّايَ." ماذا فضّل الشَّخْصُ؟', options: ['الشَّايَ', 'القَهْوَةَ', 'العَصِيرَ', 'المَاءَ'], correctIndex: 0, explanationAr: 'صرح بتفضيل الشاي.' },
  { id: 49, skill: 'listening', skillAr: 'الاستماع والفهم المسموع', subSkillAr: 'فهم الأرقام والتعليمات', cefr: 'A2', question: 'سمعتَ التوجيه: "افْتَحِ الكِتَابَ صَفْحَةَ عِشْرِينَ". ما الرقم المطلوب؟', options: ['20', '10', '30', '2'], correctIndex: 0, explanationAr: 'عشرين تعني 20.' },
  { id: 50, skill: 'listening', skillAr: 'الاستماع والفهم المسموع', subSkillAr: 'تحليل الأسباب والعلل', cefr: 'B2', question: 'استمعتَ للخبر: "تَأَخَّرَتِ الطَّائِرَةُ بِسَبَبِ الضَّبَابِ". سبب تأخّر الطائرة هو:', options: ['الضَّبَابُ', 'المَطَرُ', 'الرِّيَاحُ', 'الثَّلْجُ'], correctIndex: 0, explanationAr: 'الضباب هو السبب المذكور بالنص.' },

  // 6. Speaking & Communication (51-60)
  { id: 51, skill: 'speaking', skillAr: 'التحدث والتواصل', subSkillAr: 'طلب المساعدة بأدب', cefr: 'A1', question: 'لطلب المساعدة بأدب ولطف تقول:', options: ['لو سَمَحْتَ، هَلْ تُسَاعِدُنِي؟', 'أَعْطِنِي هَذَا فَوْراً', 'اذْهَبْ مِنْ هُنَا', 'لا أُرِيدُ شَيْئاً'], correctIndex: 0, explanationAr: 'لو سمحت هي صيغة أدب شائعة.' },
  { id: 52, skill: 'speaking', skillAr: 'التحدث والتواصل', subSkillAr: 'التعريف بالنفس', cefr: 'A1', question: 'كيف تعرّف بنفسك أمام زملائك الجدد؟', options: ['مَرْحَبًا، أَنَا اسْمِي سَارَةُ', 'مَا اسْمُكَ أَنْتَ؟', 'هَذَا كِتَابِي', 'أَيْنَ المَدْرَسَةُ؟'], correctIndex: 0, explanationAr: 'الصيغة الصحيحة هي الذكر المباشر للاسم مع الترحيب.' },
  { id: 53, skill: 'speaking', skillAr: 'التحدث والتواصل', subSkillAr: 'السؤال عن الأسعار والتسوق', cefr: 'A2', question: 'عندما تشتري شيئاً من البائع وتسأله عن السعر، تقول:', options: ['كَمْ ثَمَنُ هَذَا؟', 'كَيْفَ حالُكَ؟', 'أَيْنَ البَيْتُ؟', 'كَمِ السَّاعَةُ؟'], correctIndex: 0, explanationAr: 'كم ثمن هذا تسأل عن القيمة النقدية.' },
  { id: 54, skill: 'speaking', skillAr: 'التحدث والتواصل', subSkillAr: 'تقديم الاعتذار', cefr: 'A1', question: 'عندما تريد الاعتذار عن خطأ غير مقصود، تقول:', options: ['أَنَا آسِفٌ', 'شُكْراً', 'مَعَ السَّلامَةِ', 'أَهْلاً'], correctIndex: 0, explanationAr: 'أنا أسف تعبر عن الاعتذار.' },
  { id: 55, skill: 'speaking', skillAr: 'التحدث والتواصل', subSkillAr: 'التعبير عن الرأي والتفضيل', cefr: 'A2', question: 'للتعبير عن رأيك الإيجابي في وجبة طعام لديدة تقول:', options: ['هَذَا الطَّعَامُ لَذِيذٌ جِدًّا', 'هَذَا الكِتَابُ مُفِيدٌ', 'الطَّقْسُ بَارِدٌ', 'لا أَعْرِفُ مَنْ هُوَ'], correctIndex: 0, explanationAr: 'الوصف بلذيذ يعبر عن المذاق.' },
  { id: 56, skill: 'speaking', skillAr: 'التحدث والتواصل', subSkillAr: 'مواعيد ووسائل المواصلات', cefr: 'B1', question: 'السؤال المناسب للسؤال عن وقت انطلاق القطار هو:', options: ['مَتَى يَنْطَلِقُ القِطَارُ؟', 'أَيْنَ القِطَارُ؟', 'مَنْ رَكِبَ القِطَارَ؟', 'كَيْفَ القِطَارُ؟'], correctIndex: 0, explanationAr: 'متى ينطلق تسأل عن الزمان المحدد.' },
  { id: 57, skill: 'speaking', skillAr: 'التحدث والتواصل', subSkillAr: 'الحديث عن المهنة والعمل', cefr: 'A2', question: 'عندما يسألك أحد: "ماذا تعمل؟"، تجيب عن مهنتك بـ:', options: ['أَنَا مُهَنْدِسٌ فِي شَرِكَةٍ', 'أَنَا فِي البَيْتِ', 'أَنَا بِخَيْرٍ', 'عُمْرِي 25 سَنَةً'], correctIndex: 0, explanationAr: 'إجابة تحديد الوظيفة والمهنة.' },
  { id: 58, skill: 'speaking', skillAr: 'التحدث والتواصل', subSkillAr: 'التعبير عن الخطط المستقبلية', cefr: 'B1', question: 'للتعبير عن نيتك السفر في المستقبل تقول:', options: ['سَأُسَافِرُ إِلَى مِصْرَ الشَّهْرَ القَادِمَ', 'سَافَرْتُ أَمْسِ', 'لَمْ أُسَافِرْ أَبَداً', 'أَنَا فِي المَطَارِ الآنَ'], correctIndex: 0, explanationAr: 'السين والتسويف للشهر القادم تدل على المستقبل.' },
  { id: 59, skill: 'speaking', skillAr: 'التحدث والتواصل', subSkillAr: 'تقديم الاقتراحات والمبادرات', cefr: 'B2', question: 'لتقديم اقتراح لأصدقائك بزيارة الحديقة تقول:', options: ['مَا رَأْيُكُمْ أَنْ نَذْهَبَ إِلَى الحَدِيقَةِ؟', 'اذْهَبُوا وَحْدَكُمْ', 'الحَدِيقَةُ بَعِيدَةٌ', 'لا أُحِبُّ الحَدَائِقَ'], correctIndex: 0, explanationAr: 'ما رأيكم صيغة استشارت واقتراح.' },
  { id: 60, skill: 'speaking', skillAr: 'التحدث والتواصل', subSkillAr: 'توديع المسافرين والتهاني', cefr: 'A2', question: 'لتوديع صديق مسافر تقول له معبرًا عن تمنياتك:', options: ['أَتَمَنَّى لَكَ رِحْلَةً سَعِيدَةً', 'صَبَاحُ الخَيْرِ', 'عَفْواً', 'كَمِ السَّاعَةُ؟'], correctIndex: 0, explanationAr: 'أتمنى لك رحلة سعيدة تقال عند السفر.' },

  // 7. Reading Comprehension (61-70)
  { id: 61, skill: 'reading', skillAr: 'القراءة والاستيعاب', subSkillAr: 'استخراج الشخصيات النصلية', cefr: 'A1', question: 'نص: (أَحْمَدُ طَالِبٌ نَشِيطٌ يَسْتَيْقِظُ فِي السَّادِسَةِ) - ما اسم الطالب؟', options: ['أَحْمَدُ', 'مَحْمُودٌ', 'خَالِدٌ', 'عُمَرُ'], correctIndex: 0, explanationAr: 'أحمد هو الشخصية الرئيسة بالنص.' },
  { id: 62, skill: 'reading', skillAr: 'القراءة والاستيعاب', subSkillAr: 'استخلاص الوقت المباشر', cefr: 'A1', question: 'متى يستيقظ أحمد في النص السكني؟', options: ['في الساعة السادسة', 'في الساعة السابعة', 'في الساعة الخامسة', 'في الظهيرة'], correctIndex: 0, explanationAr: 'النص ذكر الساعة السادسة.' },
  { id: 63, skill: 'reading', skillAr: 'القراءة والاستيعاب', subSkillAr: 'المعالم والمشاركون', cefr: 'A2', question: 'مع من يتناول أحمد الفطور في النص؟', options: ['مع أسرته', 'مع أصدقائه', 'بمفرده', 'مع معلمه'], correctIndex: 0, explanationAr: 'النص صرّح بـ مع أسرته.' },
  { id: 64, skill: 'reading', skillAr: 'القراءة والاستيعاب', subSkillAr: 'استخراج وسيلة التنقل', cefr: 'A2', question: 'كيف يذهب أحمد إلى المدرسة؟', options: ['بالحافلة', 'سيراً على الأقدام', 'بالسيارة', 'بالقطار'], correctIndex: 0, explanationAr: 'الذهاب بالحافلة.' },
  { id: 65, skill: 'reading', skillAr: 'القراءة والاستيعاب', subSkillAr: 'صفات الشخصيات', cefr: 'A2', question: 'الصفة المباشرة التي وُصف بها أحمد في النص أنه:', options: ['نشيط', 'كسلان', 'بطيء', 'متأخر'], correctIndex: 0, explanationAr: 'طالب نشيط.' },
  { id: 66, skill: 'reading', skillAr: 'القراءة والاستيعاب', subSkillAr: 'تحديد الموضوع الرئيس', cefr: 'A2', question: 'نص: (فَصْلُ الرَّبِيعِ أَبْهَى فُصُولِ السَّنَةِ) - الفصل المذكور هو:', options: ['الربيع', 'الصيف', 'الخريف', 'الشتاء'], correctIndex: 0, explanationAr: 'الحديث عن الربيع.' },
  { id: 67, skill: 'reading', skillAr: 'القراءة والاستيعاب', subSkillAr: 'استخلاص التفاصيل الدقيقة', cefr: 'B1', question: 'ماذا تفعل الطيور في فصل الربيع حسب النص؟', options: ['تغرد', 'تنام', 'تطير بعيداً', 'تختفي'], correctIndex: 0, explanationAr: 'وتغرد الطيور.' },
  { id: 68, skill: 'reading', skillAr: 'القراءة والاستيعاب', subSkillAr: 'وصف البيئة والمظاهر', cefr: 'B1', question: 'كيف تكون الحدائق في فصل الربيع حسب النص؟', options: ['خضراء جميلة', 'جافة', 'بيضاء', 'مظلمة'], correctIndex: 0, explanationAr: 'وتكون الحدائق خضراء جميلة.' },
  { id: 69, skill: 'reading', skillAr: 'القراءة والاستيعاب', subSkillAr: 'فهم مفردات النصوص', cefr: 'B2', question: 'كلمة (أَبْهَى) في النص تعني:', options: ['أَجْمَلُ', 'أَصْغَرُ', 'أَطْوَلُ', 'أَبْرَدُ'], correctIndex: 0, explanationAr: 'أبها هي أجمل وأحسن.' },
  { id: 70, skill: 'reading', skillAr: 'القراءة والاستيعاب', subSkillAr: 'الفكرة الرئيسة والهدف', cefr: 'B2', question: 'الفكرة الرئيسة الشاملة للنص هي:', options: ['جمال فصل الربيع', 'أنواع الأشجار', 'هجرة الطيور', 'زراعة الحدائق'], correctIndex: 0, explanationAr: 'النص يدور كاملاً حول الربيع وجماله.' },

  // 8. Writing & Orthography (71-80)
  { id: 71, skill: 'writing', skillAr: 'الكتابة والإملاء', subSkillAr: 'تحليل الحروف وتجميعها', cefr: 'A1', question: 'الترتيب الصحيح للحروف لتكوين كلمة (قَلَمٌ) هو:', options: ['ق - ل - م', 'م - ل - ق', 'ق - م - ل', 'ل - ق - م'], correctIndex: 0, explanationAr: 'ترتيب حروف قلم هو ق، ل، م.' },
  { id: 72, skill: 'writing', skillAr: 'الكتابة والإملاء', subSkillAr: 'التنوين وكتابة التنوين', cefr: 'A1', question: 'الكلمة المكتوبة بشكل إملائي صحيح دون إضافة نون زائدة هي:', options: ['كِتَابٌ', 'كِتَابن', 'كِتَابٍن', 'كِتَابُن'], correctIndex: 0, explanationAr: 'التنوين صوت نون ولا يكتب نوناً صريحة.' },
  { id: 73, skill: 'writing', skillAr: 'الكتابة والإملاء', subSkillAr: 'علامات الترقيم (الاستفهام)', cefr: 'A1', question: 'اختر علامة الترقيم المناسبة في نهاية: (مَا اسْمُكَ ...)', options: ['؟', '!', '.', '،'], correctIndex: 0, explanationAr: 'علامة الاستفهام للسؤال.' },
  { id: 74, skill: 'writing', skillAr: 'الكتابة والإملاء', subSkillAr: 'علامات الترقيم (التعجب)', cefr: 'A2', question: 'علامة الترقيم المناسبة للجملة التعجبية: (مَا أَجْمَلَ السَّمَاءَ...)', options: ['!', '؟', '.', ':'], correctIndex: 0, explanationAr: 'علامة التعجب للتعجب (!).' },
  { id: 75, skill: 'writing', skillAr: 'الكتابة والإملاء', subSkillAr: 'ترتيب الكلمات لتكوين جملة', cefr: 'A2', question: 'الترتيب الصحيح للجملة: (المَدْرَسَةِ - إِلَى - الطَّالِبُ - ذَهَبَ)', options: ['ذَهَبَ الطَّالِبُ إِلَى المَدْرَسَةِ', 'إِلَى المَدْرَسَةِ ذَهَبَ الطَّالِبُ', 'الطَّالِبُ ذَهَبَ المَدْرَسَةِ إِلَى', 'ذَهَبَ المَدْرَسَةِ إِلَى الطَّالِبُ'], correctIndex: 0, explanationAr: 'فعل + فاعل + حرف جر + اسم مجرور.' },
  { id: 76, skill: 'writing', skillAr: 'الكتابة والإملاء', subSkillAr: 'همزة القطع', cefr: 'B1', question: 'اختر الكلمة التي تحتوي على (همزة قطع) رسمت بوضوح:', options: ['أَحْمَدُ', 'اسْمٌ', 'ابْنٌ', 'اسْتَغْفَرَ'], correctIndex: 0, explanationAr: 'أحمد همزة قطع تكتب وتنطق.' },
  { id: 77, skill: 'writing', skillAr: 'الكتابة والإملاء', subSkillAr: 'همزة الوصل', cefr: 'B1', question: 'الكلمة التي تبدأ بـ (همزة وصل) تسقط في الدرج هي:', options: ['اكْتُبْ', 'أَنَا', 'أُمِّي', 'أَبِي'], correctIndex: 0, explanationAr: 'اكتب في أمر الثلاثي همزة وصل.' },
  { id: 78, skill: 'writing', skillAr: 'الكتابة والإملاء', subSkillAr: 'الهمزة المتوسطة', cefr: 'B2', question: 'اختر الكتابة الصحيحة للهمزة المتوسطة في: (مَسْـ...ـلَة)', options: ['مَسْأَلَة', 'مَسْؤَلَة', 'مَسْئَلَة', 'مَسْآلَة'], correctIndex: 0, explanationAr: 'الهمزة مفتوحة بعد ساكن فترسم على الألف.' },
  { id: 79, skill: 'writing', skillAr: 'الكتابة والإملاء', subSkillAr: 'المطابقة بين النعت والمنعوت', cefr: 'B2', question: 'اختر الجملة المكتوبة بنحو وإملاء صحيحين:', options: ['قَرَأَ الطَّالِبُ كِتَاباً مُفِيداً', 'قَرَأَ الطَّالِبَ كِتَابٌ مُفِيدٌ', 'قَرَا الطَّالِبُ كِتَابًا مُفِيدً', 'قَرَأَ الطَّالِبُ كِتَابًا مُفِيدٌ'], correctIndex: 0, explanationAr: 'الفاعل مرفوع والمفعول والصفة منصوبان بالتنوين.' },
  { id: 80, skill: 'writing', skillAr: 'الكتابة والإملاء', subSkillAr: 'تنوين الفتح على الهمزة المتطرفة', cefr: 'B2', question: 'ما التنوين الصحيح لكلمة (مَاء) بالنصب دون إلف زائدة؟', options: ['مَاءً', 'مَاءاً', 'مَاءن', 'مَاءٌ'], correctIndex: 0, explanationAr: 'الهمزة المتطرفة المسبوقة بألف لا تزاد بعدها ألف تنوين.' }
];
